if [ "$GENERATE_DATFILE" = "true" ]; then
            cat << 'EOF' > export_version_meta.py
          import sys, os, json, zlib, hashlib
          import firmware_downloader

          tag = sys.argv[1]
          folder_name = sys.argv[2]
          # ...
          identity_res, _ = firmware_downloader.find_firmware_identity(folder_name)
